#***************************************************************************************
# ysyxSoC Makefile — thin wrapper around cargo + mill
#
# 三步构建流程:
#   make verilog    — Chisel → SystemVerilog
#   make verilate   — SystemVerilog → Verilator C++ 库
#   make build      — Rust + C++ FFI → 仿真可执行文件 (cargo)
#
# 也可以一步到位:
#   make run IMG=<bin>
#***************************************************************************************

# =============================== 路径定义 ===============================

NPC_HOME     ?= $(abspath .)
BUILD_DIR    := $(NPC_HOME)/build
MESON_BDIR   := $(BUILD_DIR)/meson
MILL         := mill

GUEST_ISA    ?= riscv32

# =============================== meson setup ===============================

$(MESON_BDIR)/build.ninja:
	meson setup $(MESON_BDIR) $(NPC_HOME) \
		-Dguest_isa=$(GUEST_ISA)

meson-setup: $(MESON_BDIR)/build.ninja

# =============================== Step 0: SoCConfig.scala ===============================

SOC_CONFIG_SCALA := $(NPC_HOME)/src/scala/SoCConfig.scala
MESON_SOC_CONFIG := $(MESON_BDIR)/SoCConfig.scala

$(SOC_CONFIG_SCALA): $(MESON_SOC_CONFIG)
	@cp $< $@
	@echo "=== Updated SoCConfig.scala from meson ==="

$(MESON_SOC_CONFIG): $(MESON_BDIR)/build.ninja
	@: # generated by meson setup

# =============================== Step 1: make verilog ===============================
# Chisel → SystemVerilog (mill)

SCALA_FILES := $(shell find src/scala -name "*.scala" ! -name "SoCConfig.scala" 2>/dev/null)

RTL_DIR    := $(BUILD_DIR)/rtl
V_SIM      := $(RTL_DIR)/NPCSoC.sv

$(V_SIM): $(SCALA_FILES) $(SOC_CONFIG_SCALA)
	@mkdir -p $(RTL_DIR)
	$(MILL) -i ysyxsoc.runMain ysyx.ElaborateNPCSoC --target-dir $(RTL_DIR)

verilog: $(V_SIM)

# =============================== Step 2: make verilate ===============================
# SystemVerilog → Verilator C++ 静态库

VERILATOR      ?= verilator
VERILATOR_TOP  := NPCSoC
VERILATOR_MDIR := $(BUILD_DIR)/obj-verilator
VERILATOR_MK   := $(VERILATOR_MDIR)/V$(VERILATOR_TOP).mk
VERILATOR_LIB  := $(VERILATOR_MDIR)/V$(VERILATOR_TOP)__ALL.a

VERILATOR_SRCS := $(V_SIM)
VERILATOR_SRCS += $(shell find $(RTL_DIR) -name "*.sv" 2>/dev/null)
VERILATOR_PERIP_SRCS := $(shell find src/verilog -name "*.v" 2>/dev/null)
VERILATOR_SRCS += $(VERILATOR_PERIP_SRCS)

VERILATOR_INCS := -I$(NPC_HOME)/src/verilog/spi/rtl
VERILATOR_INCS += -I$(NPC_HOME)/src/verilog/uart16550/rtl
VERILATOR_INCS += -I$(RTL_DIR)/verification
VERILATOR_INCS += -I$(RTL_DIR)/verification/assert
VERILATOR_INCS += -I$(RTL_DIR)/verification/assume
VERILATOR_INCS += -I$(RTL_DIR)/verification/cover

VERILATOR_DEFINES := $(if $(findstring true,$(DIFFTEST)),+define+CONFIG_DIFFTEST,)
VERILATOR_DEFINES += $(if $(findstring true,$(VERILATOR_TRACE)),+define+CONFIG_VERILATOR_TRACE,)

$(VERILATOR_MK): $(V_SIM) $(VERILATOR_PERIP_SRCS)
	@echo "=== Verilating $(VERILATOR_TOP) ==="
	@mkdir -p $(VERILATOR_MDIR)
	$(VERILATOR) --cc $(VERILATOR_SRCS) \
		--Mdir $(VERILATOR_MDIR) \
		--top-module $(VERILATOR_TOP) \
		--timescale "1ns/1ns" \
		--trace-fst --no-timing --autoflush --assert \
		-O2 -Wall -Wno-fatal \
		$(VERILATOR_INCS) \
		$(VERILATOR_DEFINES) \
		-CFLAGS "-std=c++17 -O2"

$(VERILATOR_LIB): $(VERILATOR_MK)
	@echo "=== Building Verilator library ==="
	$(MAKE) -C $(VERILATOR_MDIR) -f V$(VERILATOR_TOP).mk

verilate: $(VERILATOR_LIB)

# =============================== Step 3: make build ===============================
# Rust + C++ FFI → 仿真可执行文件 (cargo build)

RELEASE ?= 1
BINARY := $(if $(findstring 1,$(RELEASE)),target/release/npc,target/debug/npc)

build:
	unset CC CXX && cargo build $(if $(findstring 1,$(RELEASE)),--release,)

release: verilate
	$(MAKE) build RELEASE=1

# =============================== make all ===============================
# 完整流程: verilog → verilate → build

all: verilate build

# =============================== 运行 & 调试 ===============================

override ARGS ?= --log=$(BUILD_DIR)/npc-log.txt
IMG ?=

NPC_EXEC = $(BINARY) $(ARGS) -i $(IMG)

run: all
	RUST_LOG=info $(NPC_EXEC)

gdb: all
	gdb -s $(BINARY) --args $(NPC_EXEC)

# =============================== 配置 ===============================

menuconfig: $(MESON_BDIR)/build.ninja
	meson configure $(NPC_HOME)

# =============================== 开发工具 ===============================

wave:
	@gtkwave $(BUILD_DIR)/npc_core.fst

dev-init:
	git submodule update --init --recursive
	cd rocket-chip && git apply ../patch/rocket-chip.patch

bsp:
	$(MILL) -i mill.bsp.BSP/install

idea:
	$(MILL) -i mill.idea.GenIdea/idea

reformat:
	$(MILL) -i __.reformat

checkformat:
	$(MILL) -i __.checkFormat

# =============================== 清理 ===============================

clean:
	-rm -rf $(BUILD_DIR)

distclean: clean
	-rm -f $(SOC_CONFIG_SCALA)

clean-all: distclean

# =============================== 帮助 ===============================

help:
	@echo "ysyxSoC Makefile (cargo backend)"
	@echo ""
	@echo "三步构建:"
	@echo "  verilog            — Step 1: Chisel → SystemVerilog"
	@echo "  verilate           — Step 2: SystemVerilog → Verilator C++ 库"
	@echo "  build              — Step 3: Rust + C++ FFI → 仿真可执行文件 (cargo, debug)"
	@echo "  release            — verilate + build (release 模式，性能更优)"
	@echo "  all                — 执行 Step 1-3"
	@echo ""
	@echo "运行与调试:"
	@echo "  run IMG=<bin>      — 全流程编译 + 运行仿真"
	@echo "  gdb IMG=<bin>      — 全流程编译 + GDB 调试"
	@echo "  wave               — 查看波形"
	@echo ""
	@echo "配置:"
	@echo "  menuconfig         — 查看/修改 meson 选项"
	@echo ""
	@echo "清理:"
	@echo "  clean              — 清理构建目录"
	@echo "  distclean          — 清理所有生成文件"

.PHONY: verilog verilate build release all
.PHONY: meson-setup
.PHONY: run gdb wave
.PHONY: menuconfig
.PHONY: dev-init bsp idea reformat checkformat
.PHONY: clean distclean clean-all help
