# ISA
option('guest_isa', type: 'combo', choices: ['riscv32'], value: 'riscv32', description: 'Guest ISA')

# SoC Address Map
option('soc_reset_vector',   type: 'string', value: '0x30000000')
option('soc_uart_base',      type: 'string', value: '0x10000000')
option('soc_uart_size',      type: 'string', value: '0x1000')
option('soc_gpio_base',      type: 'string', value: '0x10002000')
option('soc_gpio_size',      type: 'string', value: '0x10')
option('soc_keyboard_base',  type: 'string', value: '0x10011000')
option('soc_keyboard_size',  type: 'string', value: '0x8')
option('soc_vga_base',       type: 'string', value: '0x21000000')
option('soc_vga_size',       type: 'string', value: '0x200000')
option('soc_spi_ctrl_base',  type: 'string', value: '0x10001000')
option('soc_spi_ctrl_size',  type: 'string', value: '0x1000')
option('soc_flash_base',     type: 'string', value: '0x30000000')
option('soc_flash_size',     type: 'string', value: '0x10000000')
option('soc_psram_base',     type: 'string', value: '0x80000000')
option('soc_psram_size',     type: 'string', value: '0x400000')
option('soc_mrom_base',      type: 'string', value: '0x20000000')
option('soc_mrom_size',      type: 'string', value: '0x1000')
option('soc_sram_base',      type: 'string', value: '0x0f000000')
option('soc_sram_size',      type: 'string', value: '0x2000')
option('soc_sdram_base',     type: 'string', value: '0xa0000000')
option('soc_sdram_size',     type: 'string', value: '0x2000000')
