#!/usr/bin/env bash
#***************************************************************************************
# Copyright (c) 2014-2024 Zihao Yu, Nanjing University
#
# NPC is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
#
# See the Mulan PSL v2 for more details.
#**************************************************************************************/

# Generate SoCConfig.scala from Kconfig .config file
# Usage: ./gen-scala-config.sh <config_file> <output_file>

CONFIG_FILE="${1:-.config}"
OUTPUT_FILE="${2:-src/scala/SoCConfig.scala}"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: Config file '$CONFIG_FILE' not found!" >&2
    echo "Please run 'make menuconfig' first." >&2
    exit 1
fi

# Function to convert hex string to Scala Long literal
# Input: 0x10000000 -> Output: 0x10000000L
hex_to_scala() {
    local val="$1"
    # Remove quotes if present
    val="${val%\"}"
    val="${val#\"}"
    echo "${val}L"
}

# Function to convert config name to Scala camelCase
# Input: SOC_UART_BASE -> Output: uartBase
config_to_scala_name() {
    local name="$1"
    # Remove SOC_ prefix
    name="${name#SOC_}"
    # Convert to lowercase and camelCase
    echo "$name" | awk '{
        n = split(tolower($0), parts, "_")
        result = parts[1]
        for (i = 2; i <= n; i++) {
            result = result toupper(substr(parts[i], 1, 1)) substr(parts[i], 2)
        }
        print result
    }'
}

# Extract SOC_* configs from .config file
declare -A configs
while IFS='=' read -r key value; do
    # Skip comments and empty lines
    [[ "$key" =~ ^# ]] && continue
    [[ -z "$key" ]] && continue
    
    # Only process CONFIG_SOC_* entries
    if [[ "$key" =~ ^CONFIG_SOC_ ]]; then
        # Remove CONFIG_ prefix
        config_name="${key#CONFIG_}"
        configs["$config_name"]="$value"
    fi
done < "$CONFIG_FILE"

# Generate Scala file to OUTPUT_FILE
{
cat << 'HEADER'
// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by scripts/gen-scala-config.sh from Kconfig .config
// Run 'make menuconfig' to modify these values
// ============================================================================

package ysyx

/** SoC Address Configuration
  *
  * This object contains all address-related configuration values
  * extracted from Kconfig. These values are used by both hardware
  * (Chisel) and simulation (C++) code.
  */
object SoCConfig {
HEADER

# Output each config as a Scala val
for key in $(echo "${!configs[@]}" | tr ' ' '\n' | sort); do
    value="${configs[$key]}"
    scala_name=$(config_to_scala_name "$key")
    scala_value=$(hex_to_scala "$value")
    echo "  val $scala_name: Long = $scala_value"
done

cat << 'FOOTER'
}
FOOTER
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
