#***************************************************************************************
# Copyright (c) 2014-2024 Zihao Yu, Nanjing University
#
# NPC is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
#
# See the Mulan PSL v2 for more details.
#**************************************************************************************/

# Sanity check
ifeq ($(wildcard $(NPC_HOME)/src/cxx/npc-main.cc),)
  $(error NPC_HOME=$(NPC_HOME) is not a NPC repo)
endif

# Include variables and rules generated by menuconfig
-include $(NPC_HOME)/include/config/auto.conf
-include $(NPC_HOME)/include/config/auto.conf.cmd

remove_quote = $(patsubst "%",%,$(1))

# Extract variabls from menuconfig
GUEST_ISA ?= $(call remove_quote,$(CONFIG_ISA))
NAME    = $(GUEST_ISA)-npc

# =============================== gather file lists ===============================

# Include all filelist.mk to merge file lists
FILELIST_MK = $(shell find -L ./src/cxx -name "filelist.mk")
include $(FILELIST_MK)

# =============================== 表达式求值 (flex/bison) ===============================

# Flex/Bison sources and generated files
LEX_SRC  := src/cxx/monitor/sdb/expr.l
YACC_SRC := src/cxx/monitor/sdb/expr.y
LEX_GEN  := $(LEX_SRC:.l=.lex.c)
YACC_GEN := $(YACC_SRC:.y=.tab.c)
YACC_HDR := $(YACC_SRC:.y=.tab.h)
SRCS-y   += $(LEX_GEN) $(YACC_GEN)

# Generate parser/lexer sources
$(YACC_GEN) $(YACC_HDR): $(YACC_SRC)
	@echo + BISON $<
	@bison -d -o $(YACC_GEN) $(YACC_SRC)

$(LEX_GEN): $(LEX_SRC) $(YACC_HDR)
	@echo + FLEX $<
	@flex -o $(LEX_GEN) $(LEX_SRC)

# =============================== 搜集文件列表 ===============================

# Filter out directories and files in blacklist to obtain the final set of source files
DIRS-BLACKLIST-y += $(DIRS-BLACKLIST)
SRCS-BLACKLIST-y += $(if $(DIRS-BLACKLIST-y), $(shell find -L $(DIRS-BLACKLIST-y) -name "*.c"),)
SRCS-BLACKLIST-y += $(SRCS-BLACKLIST)
SRCS-y += $(if $(DIRS-y), $(shell find -L $(DIRS-y) -name "*.c"),)
SRCS = $(filter-out $(SRCS-BLACKLIST-y),$(SRCS-y))
SRCS := $(sort $(SRCS))

# =============================== 选择编译器 ===============================

# Extract compiler and options from menuconfig
ifneq ($(CONFIG_CC),)
# gcc, g++, clang
CC = $(call remove_quote,$(CONFIG_CC))
endif

# =============================== 编译优化、调试信息、地址安全检查 ===============================

CFLAGS_BUILD += $(call remove_quote,$(CONFIG_CC_OPT))
CFLAGS_BUILD += $(if $(CONFIG_CC_LTO),-flto,) # LDFLAGS
CFLAGS_BUILD += $(if $(CONFIG_CC_DEBUG),-Og -ggdb3,)
# LDFLAGS 会链接, 如果开了地址安全检查
CFLAGS_BUILD += $(if $(CONFIG_CC_ASAN),-fsanitize=address,)
# Disable PIE for NixOS compatibility (绝对地址重定位需要)
CFLAGS_BUILD += -fno-pie
CFLAGS += $(CFLAGS_BUILD)
LDFLAGS += $(CFLAGS_BUILD) -no-pie

# =============================== ITRACE ===============================

CFLAGS_TRACE += -DITRACE_COND=$(if $(CONFIG_ITRACE_COND),$(call remove_quote,$(CONFIG_ITRACE_COND)),true)
CFLAGS += $(CFLAGS_TRACE) 

# =============================== guest os 的 ISA ===============================

CFLAGS += -D__GUEST_ISA__=$(GUEST_ISA)

# =============================== menuconfig ===============================

# Include rules for menuconfig
include $(NPC_HOME)/scripts/config.mk

# =============================== 构建 AM 系统 ===============================

# 生成二进制 NPC
include $(NPC_HOME)/scripts/build.mk

include $(NPC_HOME)/tools/difftest.mk

compile_git:
	$(call git_commit, "compile NPC")
$(BINARY):: compile_git

# Some convenient rules

override ARGS ?= --log=$(BUILD_DIR)/npc-log.txt
override ARGS += $(ARGS_DIFF)

# Command to execute NPC
IMG ?=
NPC_EXEC := $(BINARY) $(ARGS) $(IMG)

run-env: $(BINARY) $(DIFF_REF_SO)

run: run-env
	$(call git_commit, "run NPC")
	$(NPC_EXEC)

gdb: run-env
	$(call git_commit, "gdb NPC")
	gdb -s $(BINARY) --args $(NPC_EXEC)

clean-tools = $(dir $(shell find ./tools -maxdepth 2 -mindepth 2 -name "Makefile"))

$(clean-tools):
	-@$(MAKE) -s -C $@ clean
clean-lex-yacc:
	@rm -f $(LEX_GEN) $(YACC_GEN) $(YACC_HDR)
clean-tools: $(clean-tools)
clean-all: clean distclean clean-tools clean-lex-yacc

.PHONY: run gdb run-env clean-tools clean-all $(clean-tools) clean-lex-yacc
