// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by meson from SoCConfig.scala.in
// To modify these values, run: meson configure build/meson -Dsoc_xxx=0xNNN

package ysyx

object SoCConfig {
  val resetVector: Long = 0x3000_0000L
  val uartBase: Long = 0x10000000L
  val uartSize: Long = 0x1000L
  val gpioBase: Long = 0x10002000L
  val gpioSize: Long = 0x10L
  val keyboardBase: Long = 0x10011000L
  val keyboardSize: Long = 0x8L
  val vgaBase: Long = 0x21000000L
  val vgaSize: Long = 0x200000L
  val syncDiskBase: Long = 0x10001000L
  val syncDiskSize: Long = 0x1000L
  val xipFlashBase: Long = 0x30000000L
  val xipFlashSize: Long = 0x10000000L
  val clintBase: Long = 0x02000000L
  val clintSize: Long = 0x10000L
  val plicBase: Long = 0x0c000000L
  val plicSize: Long = 0x400000L
  val sdramBase: Long = 0x80000000L
  val sdramSize: Long = 0x10000000L
}
